/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/actions/ActionCard.vue')['default']
    ActionForm: typeof import('./src/components/actions/ActionForm.vue')['default']
    DocumentCard: typeof import('./src/components/documents/DocumentCard.vue')['default']
    DocumentForm: typeof import('./src/components/documents/DocumentForm.vue')['default']
    HeaderLayout: typeof import('./src/components/layout/HeaderLayout.vue')['default']
    IndicatorCard: typeof import('./src/components/indicators/IndicatorCard.vue')['default']
    IndicatorForm: typeof import('./src/components/indicators/IndicatorForm.vue')['default']
    InputField: typeof import('./src/components/form/InputField.vue')['default']
    MyButton: typeof import('./src/components/ui/MyButton.vue')['default']
    NumberField: typeof import('./src/components/form/NumberField.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./src/components/form/SelectField.vue')['default']
    SidebarMenu: typeof import('./src/components/layout/SidebarMenu.vue')['default']
    TextAreaField: typeof import('./src/components/form/TextAreaField.vue')['default']
  }
}
