/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/actions/ActionCard.vue')['default']
    ActionForm: typeof import('./src/components/actions/ActionForm.vue')['default']
    AssignmentForm: typeof import('./src/components/equipment/AssignmentForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DocumentCard: typeof import('./src/components/documents/DocumentCard.vue')['default']
    DocumentFolderSidebar: typeof import('./src/components/documents/DocumentFolderSidebar.vue')['default']
    DocumentForm: typeof import('./src/components/documents/DocumentForm.vue')['default']
    DocumentVersionModal: typeof import('./src/components/documents/DocumentVersionModal.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EquipmentForm: typeof import('./src/components/equipment/EquipmentForm.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HeaderLayout: typeof import('./src/components/layout/HeaderLayout.vue')['default']
    IconPicker: typeof import('./src/components/common/IconPicker.vue')['default']
    IndicatorCard: typeof import('./src/components/indicators/IndicatorCard.vue')['default']
    IndicatorForm: typeof import('./src/components/indicators/IndicatorForm.vue')['default']
    InputField: typeof import('./src/components/form/InputField.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MaintenanceForm: typeof import('./src/components/equipment/MaintenanceForm.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    MyButton: typeof import('./src/components/ui/MyButton.vue')['default']
    NumberField: typeof import('./src/components/form/NumberField.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    ParticipantManager: typeof import('./src/components/trainings/ParticipantManager.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectField: typeof import('./src/components/form/SelectField.vue')['default']
    SessionList: typeof import('./src/components/trainings/SessionList.vue')['default']
    SidebarMenu: typeof import('./src/components/layout/SidebarMenu.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TextAreaField: typeof import('./src/components/form/TextAreaField.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToolboxTalkForm: typeof import('./src/components/planning/ToolboxTalkForm.vue')['default']
    TrainingCard: typeof import('./src/components/trainings/TrainingCard.vue')['default']
    VisitForm: typeof import('./src/components/planning/VisitForm.vue')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
