/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/actions/ActionCard.vue')['default']
    ActionForm: typeof import('./src/components/actions/ActionForm.vue')['default']
    ActionTypeManager: typeof import('./src/components/actions/ActionTypeManager.vue')['default']
    AssignmentForm: typeof import('./src/components/equipment/AssignmentForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    CategoryManagement: typeof import('./src/components/settings/CategoryManagement.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DocumentFolderSidebar: typeof import('./src/components/documents/DocumentFolderSidebar.vue')['default']
    DocumentForm: typeof import('./src/components/documents/DocumentForm.vue')['default']
    DocumentSelector: typeof import('./src/components/common/DocumentSelector.vue')['default']
    DocumentVersionHistory: typeof import('./src/components/documents/DocumentVersionHistory.vue')['default']
    DocumentVersionModal: typeof import('./src/components/documents/DocumentVersionModal.vue')['default']
    EquipmentAssignments: typeof import('./src/components/equipment/detail/EquipmentAssignments.vue')['default']
    EquipmentDocuments: typeof import('./src/components/equipment/EquipmentDocuments.vue')['default']
    EquipmentForm: typeof import('./src/components/equipment/EquipmentForm.vue')['default']
    EquipmentInfo: typeof import('./src/components/equipment/detail/EquipmentInfo.vue')['default']
    EquipmentMaintenance: typeof import('./src/components/equipment/detail/EquipmentMaintenance.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FraisseLogo: typeof import('./src/components/FraisseLogo.vue')['default']
    IconPicker: typeof import('./src/components/common/IconPicker.vue')['default']
    IndicatorCard: typeof import('./src/components/indicators/IndicatorCard.vue')['default']
    IndicatorForm: typeof import('./src/components/indicators/IndicatorForm.vue')['default']
    IndicatorTypeManager: typeof import('./src/components/indicators/IndicatorTypeManager.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LinkedDocuments: typeof import('./src/components/common/LinkedDocuments.vue')['default']
    MaintenanceForm: typeof import('./src/components/equipment/MaintenanceForm.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    ParticipantManager: typeof import('./src/components/trainings/ParticipantManager.vue')['default']
    ReturnForm: typeof import('./src/components/equipment/ReturnForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SessionList: typeof import('./src/components/trainings/SessionList.vue')['default']
    StatTile: typeof import('./src/components/common/StatTile.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToolboxTalkForm: typeof import('./src/components/planning/ToolboxTalkForm.vue')['default']
    TrainingCard: typeof import('./src/components/trainings/TrainingCard.vue')['default']
    UploadNewVersionDialog: typeof import('./src/components/documents/UploadNewVersionDialog.vue')['default']
    VisitForm: typeof import('./src/components/planning/VisitForm.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
